# configs/anuraset/finetune_5pct.yaml
# ───────────────────────────────────
# Fine-tune animal2vec on the 5 % stratified subset of AnuraSet
#--------------------------------------------------------------------
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}_ft_anuraset_5pct

#--------------------------------------------------------------------
common:
  fp16: true
  log_format: json
  log_interval: 11
  tensorboard_logdir: tb
  all_gather_list_size: 6500000

checkpoint:
  save_interval: 119
  keep_last_epochs: 10
  best_checkpoint_metric: metrics/finetune/f1

#--------------------------------------------------------------------
task:
  _name: audio_ccas
  data: /manifests/validation # see below
  max_sample_size: 144000 # 3 s × 48 kHz
  min_sample_size: 1000
  min_label_size: 1
  normalize: true
  sample_rate: 48000
  with_labels: true
  unique_labels: "['SPHSUR','BOABIS','SCIPER','DENNAH','LEPLAT','RHIICT','BOALEP','BOAFAB','PHYCUV','DENMIN','ELABIC','BOAPRA','DENCRU','BOALUN','BOAALB','PHYMAR','PITAZU','PHYSAU','LEPFUS','DENNAN','PHYALB','LEPLAB','SCIFUS','BOARAN','SCIFUV','AMEPIC','LEPPOD','ADEDIP','ELAMAT','PHYNAT','LEPELE','RHISCI','SCINAS','LEPNOT','ADEMAR','BOAALM','PHYDIS','RHIORN','LEPFLA','SCIRIZ','DENELE','SCIALT']"
  conv_feature_layers: "[(127, 63, 1)] +[(512, 10, 5)] + [(512, 3, 2)] * 3 + [(512, 3, 1)] + [(512, 2, 1)] * 2"
  verbose_tensorboard_logging: true

#--------------------------------------------------------------------
dataset:
  num_workers: 16
  max_tokens: 320000 # ≈ batch of 160 s audio on 4 GPUs
  skip_invalid_size_inputs_valid_test: true
  validate_interval_updates: 250
  validate_after_updates: 10000
  train_subset: train_0 # 5 % subset (generated by --limit-fraction 0.05)
  valid_subset: valid_0

distributed_training:
  distributed_world_size: 4
  ddp_backend: legacy_ddp

criterion:
  _name: finetunecriterion
  label_smoothing: 0.02
  report_accuracy: true
  segmentation_metrics: true
  use_focal_loss: true
  metric_threshold: .175
  method: avg
  sigma_s: 0.1
  maxfilt_s: 0.1
  max_duration_s: 0.5
  lowP: 0.125

optimization:
  update_freq: [8] # ≈ effective batch 8× larger
  max_update: 13000
  lr: [1.0e-4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: cosine
  warmup_updates: 2000
  warmup_init_lr: 1e-10
  min_lr: 5e-06

#--------------------------------------------------------------------
model:
  _name: wav2vec_ccas_finetune
  w2v_path: animal2vec_large_pretrained_MeerKAT_240507.pt # ⬚ pretrained ckpt
  freeze_finetune_updates: 10000
  feature_grad_mult: 0.0
  apply_mask: true
  average_top_k_layers: 16
  mask_prob: 1.1
  mask_length: 2
  mask_channel_prob: 0.5
  mask_channel_length: 64
  dropout: 0.1
  dropout_input: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.2
  final_dropout: 0.0
  layerdrop: 0.1
  drop_path: 0.0
  target_mixup: true
  source_mixup: 0.5
  mixup_prob: 1.0
  same_mixup: true
  mixing_window_length: 0.05
  gain_mode: A_weighting
  load_pretrain_weights: false
#--------------------------------------------------------------------
